[[Mongoose]]
arch = "aarch64"
git-tree-sha1 = "9109964c8919c3c015133256b27e73b186b2d4bb"
os = "macos"

    [[Mongoose.download]]
    sha256 = "41f49064eef8cd37400fb6e9fba56aca74720cb2d36e560f88d118562d0c6864"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+0/Mongoose.v7.19.0.aarch64-apple-darwin.tar.gz"
[[Mongoose]]
arch = "aarch64"
git-tree-sha1 = "9a135ff20af10710db222da204801823e5104fec"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "a3e9823b6128368026fa2d69375481d31a3cdfae8469e52c509374cdae1954e9"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+0/Mongoose.v7.19.0.aarch64-linux-gnu.tar.gz"
[[Mongoose]]
arch = "aarch64"
git-tree-sha1 = "cbc7b3c46122ea702bba9dae2d658986f32b5055"
libc = "musl"
os = "linux"

    [[Mongoose.download]]
    sha256 = "05bc1add5813d9ceecb4303699bea3da1e63de90304bb655fcc9544a98a3521f"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+0/Mongoose.v7.19.0.aarch64-linux-musl.tar.gz"
[[Mongoose]]
arch = "aarch64"
git-tree-sha1 = "dd2187bae16b02da3d81bdd02c92405b81aa7452"
os = "freebsd"

    [[Mongoose.download]]
    sha256 = "e07e2f1802d5912034e38e955d6948806e993def1b27325d950a9a0537e933b6"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+0/Mongoose.v7.19.0.aarch64-unknown-freebsd.tar.gz"
[[Mongoose]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "66437c99bc2eb2adda377cda9d71018599112b9d"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "3f07c5b278536090bcc2d5b05e68641e1aaed0882918865bd0174c401f965a84"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+0/Mongoose.v7.19.0.armv6l-linux-gnueabihf.tar.gz"
[[Mongoose]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ab948adf5e668a1b1f35edef577af69181c00067"
libc = "musl"
os = "linux"

    [[Mongoose.download]]
    sha256 = "681fd77a499b6e611882b1ebe3498fb632026c34bda24f68ae89cb6dead1e27b"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+0/Mongoose.v7.19.0.armv6l-linux-musleabihf.tar.gz"
[[Mongoose]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "18f8b4833e808649f2b9b58218144be81d04c285"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "7689bbba39e0a0532f4e4d096edbf60aa70a3ac26d50e2056d5bdb8a5dbb5154"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+0/Mongoose.v7.19.0.armv7l-linux-gnueabihf.tar.gz"
[[Mongoose]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "81e5eb289bd5071397734172c47f798d8b1d3397"
libc = "musl"
os = "linux"

    [[Mongoose.download]]
    sha256 = "80d30d21b5e6bc4aaa5e38a7890fff92d29fedb88b069ca7a15bed1ac0433260"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+0/Mongoose.v7.19.0.armv7l-linux-musleabihf.tar.gz"
[[Mongoose]]
arch = "i686"
git-tree-sha1 = "d8fb0ab03b5d43db993bede21766839071d29df2"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "78f26593a015fce2f8fc8a16693bb6d17a441d6f5289e53496299fd7619f77a3"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+0/Mongoose.v7.19.0.i686-linux-gnu.tar.gz"
[[Mongoose]]
arch = "i686"
git-tree-sha1 = "efd2bb3ff143d05cf7f5e1bf4699de1b39b3ff26"
libc = "musl"
os = "linux"

    [[Mongoose.download]]
    sha256 = "76d5eb2e2bcb221a9f78854f184fdcc271179c6356fd5e904ebfc4d07989687d"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+0/Mongoose.v7.19.0.i686-linux-musl.tar.gz"
[[Mongoose]]
arch = "i686"
git-tree-sha1 = "3d15ff95d4c8d2d692c5796f91fb2167a47f9ac9"
os = "windows"

    [[Mongoose.download]]
    sha256 = "3caa2868a688acb44ac44e4ced1312c2fed72acdeecfe6b5dd924c5c18161286"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+0/Mongoose.v7.19.0.i686-w64-mingw32.tar.gz"
[[Mongoose]]
arch = "powerpc64le"
git-tree-sha1 = "e84cace3aceede715a3c2dff67468d82fb4f0305"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "a92d42135014bc29cbfa212c4c83b44c99dcd13078c86f3614b0d4e1a990e5ad"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+0/Mongoose.v7.19.0.powerpc64le-linux-gnu.tar.gz"
[[Mongoose]]
arch = "riscv64"
git-tree-sha1 = "904ab923d7d2eec21071c0f0491277688a9a49e1"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "9f1f45a40c2ad3ee09eeb5f85f0a227709343f66d40db501b2f7ed36609f3344"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+0/Mongoose.v7.19.0.riscv64-linux-gnu.tar.gz"
[[Mongoose]]
arch = "x86_64"
git-tree-sha1 = "83d5bbb16c2d3669009f9e21a49688e6ac798a76"
os = "macos"

    [[Mongoose.download]]
    sha256 = "c6f8b058374f88eff63e8d9c1f915675b308e3195a9446c775b188d4f4f7a562"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+0/Mongoose.v7.19.0.x86_64-apple-darwin.tar.gz"
[[Mongoose]]
arch = "x86_64"
git-tree-sha1 = "eac387a7d643fa355dbf58d15274c6fbca0ef5e1"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "1dd2200352f40a34c7113c8c864c06921a578266d1c6b128864de2b3198ea7b1"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+0/Mongoose.v7.19.0.x86_64-linux-gnu.tar.gz"
[[Mongoose]]
arch = "x86_64"
git-tree-sha1 = "bf20c8576a98545ba0f7dd8ceffa74dcd818ffa1"
libc = "musl"
os = "linux"

    [[Mongoose.download]]
    sha256 = "fb36e2478e9a256528bc0f18f397ab9724d1166d2d58b3e8c709264f88f58d38"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+0/Mongoose.v7.19.0.x86_64-linux-musl.tar.gz"
[[Mongoose]]
arch = "x86_64"
git-tree-sha1 = "7ce403a6a66036ed4823d9ba988dfb3f73db2615"
os = "freebsd"

    [[Mongoose.download]]
    sha256 = "b30564e583c04e474d12bbf377be9bd28cdd59fb52d8b46df4c509155c485fb1"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+0/Mongoose.v7.19.0.x86_64-unknown-freebsd.tar.gz"
[[Mongoose]]
arch = "x86_64"
git-tree-sha1 = "28aa1c562b9929bc80ced80af73e11d0df0b38d2"
os = "windows"

    [[Mongoose.download]]
    sha256 = "c56ccb427d3986391e66feaa951bccbe7c5a9493464aeea1454ca8b321952c6c"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+0/Mongoose.v7.19.0.x86_64-w64-mingw32.tar.gz"
