[[Mongoose]]
arch = "aarch64"
git-tree-sha1 = "0e9a74a495dc4711b140a06c42b305c10b3436c0"
os = "macos"

    [[Mongoose.download]]
    sha256 = "d1fb0c3a59e75a0359553161796f7ad8f2c8de17ce266e064d27a871590f2555"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+2/Mongoose.v7.19.0.aarch64-apple-darwin.tar.gz"
[[Mongoose]]
arch = "aarch64"
git-tree-sha1 = "ebdfec46923d493a4cf00cf7ccda7d9b117558ea"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "c200d55d67ba76fb4c33c222d06685900691fb33b3473b6da4f4289b166b53a3"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+2/Mongoose.v7.19.0.aarch64-linux-gnu.tar.gz"
[[Mongoose]]
arch = "aarch64"
git-tree-sha1 = "0280ddb0266a2c2924e80a1e34f54622b0a8b7f5"
libc = "musl"
os = "linux"

    [[Mongoose.download]]
    sha256 = "2279022723dbdccace2ad2242dedbc3d09f55d9947a60ab1db0481e9b26e6385"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+2/Mongoose.v7.19.0.aarch64-linux-musl.tar.gz"
[[Mongoose]]
arch = "aarch64"
git-tree-sha1 = "e1f4e6881ac508d33b2a086fc27ca7bffac2e63f"
os = "freebsd"

    [[Mongoose.download]]
    sha256 = "502e1bd9344a6c7045d538f7e9035f11a9a45d69213e3436fede14b855a7ecaf"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+2/Mongoose.v7.19.0.aarch64-unknown-freebsd.tar.gz"
[[Mongoose]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "76212f55104f6a159f14c5fb5268f61ee72a8061"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "8e60351f6722e01c81bbcd050644702b7aeab0c4dc2eb0b234227ee8b6b1264b"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+2/Mongoose.v7.19.0.armv6l-linux-gnueabihf.tar.gz"
[[Mongoose]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e264b2fd44235d9acd6c9843b7cb91c11f45657e"
libc = "musl"
os = "linux"

    [[Mongoose.download]]
    sha256 = "f2a31c46c78eab88524a68854ecd74ba39b3cb4f1a3f1e9b4fe6ce8c2f30ca02"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+2/Mongoose.v7.19.0.armv6l-linux-musleabihf.tar.gz"
[[Mongoose]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6b99af7649fa77936f121ff2a377600b256da033"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "cebd6fc71ae30b492acbce9f86c5913377d14db09afda06ce1191af805c793a5"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+2/Mongoose.v7.19.0.armv7l-linux-gnueabihf.tar.gz"
[[Mongoose]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "89942450c77b752c84de828f9d4d1bcd889b9f4d"
libc = "musl"
os = "linux"

    [[Mongoose.download]]
    sha256 = "06c77e99e50144742cd6ab04d3bd80305b68c5ee60376e5d3373f1b72b670e6a"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+2/Mongoose.v7.19.0.armv7l-linux-musleabihf.tar.gz"
[[Mongoose]]
arch = "i686"
git-tree-sha1 = "d3c28013c4a2f0f47a72c5983c8a4a2c7df6e0d4"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "09ab6f0d1501a7993a95327d27647bd3cb0d9684183cff062801e7443d906497"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+2/Mongoose.v7.19.0.i686-linux-gnu.tar.gz"
[[Mongoose]]
arch = "i686"
git-tree-sha1 = "45f833ac1cc0893d3969945606670ca7cc4f77be"
libc = "musl"
os = "linux"

    [[Mongoose.download]]
    sha256 = "1d951446707e204836e92b2a0413e7ffb9a2139167ea520bedf5746c451122c8"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+2/Mongoose.v7.19.0.i686-linux-musl.tar.gz"
[[Mongoose]]
arch = "i686"
git-tree-sha1 = "61fe26c637416de9ced9c3a4e8b5d93ca7f97267"
os = "windows"

    [[Mongoose.download]]
    sha256 = "dc36051ddb500d8a385e6ab9cf7008828149a264c757355ebcc61c1be0d75cca"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+2/Mongoose.v7.19.0.i686-w64-mingw32.tar.gz"
[[Mongoose]]
arch = "powerpc64le"
git-tree-sha1 = "8a726aeb61343605715143a81643e907045d9871"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "33dcdeb2e566b9fb404f3daf2297c80221deb54fe0cb54a16e2f7e93ed14a7a6"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+2/Mongoose.v7.19.0.powerpc64le-linux-gnu.tar.gz"
[[Mongoose]]
arch = "riscv64"
git-tree-sha1 = "55cd93472d6e05f64e48730ef91efe2d5a01bfab"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "9c14b8005e6e1439605a09e0bc37d984cd5e77e4714a73c7d2364995b96db246"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+2/Mongoose.v7.19.0.riscv64-linux-gnu.tar.gz"
[[Mongoose]]
arch = "x86_64"
git-tree-sha1 = "fb51dad458ca6c31b98e8fe9881a27933ac41fed"
os = "macos"

    [[Mongoose.download]]
    sha256 = "b995e49f1c2e0547a4f4bde9644bf594e8cd5dec2a2949038a1ca560bc447ced"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+2/Mongoose.v7.19.0.x86_64-apple-darwin.tar.gz"
[[Mongoose]]
arch = "x86_64"
git-tree-sha1 = "90c925da07e2afd131b1087a3a47729152c1a455"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "c5b685acbafeb78c3f0735197ca02f9db338200bd1068dadc3dd878c5cae1ef6"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+2/Mongoose.v7.19.0.x86_64-linux-gnu.tar.gz"
[[Mongoose]]
arch = "x86_64"
git-tree-sha1 = "7ad8bdd7f383ce4c807c8994af9d1e48531b72d8"
libc = "musl"
os = "linux"

    [[Mongoose.download]]
    sha256 = "7c347c769251e4b0acba8c2ae03cab66a1f5dc0ca5e29ffb0cc4cc7dea411672"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+2/Mongoose.v7.19.0.x86_64-linux-musl.tar.gz"
[[Mongoose]]
arch = "x86_64"
git-tree-sha1 = "da3cea1c7c18a1e5526bf515990a4146562b2161"
os = "freebsd"

    [[Mongoose.download]]
    sha256 = "12700218a4468b2552ac889a72a8e18728429835a664ffab013bafe13f13ff2e"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+2/Mongoose.v7.19.0.x86_64-unknown-freebsd.tar.gz"
[[Mongoose]]
arch = "x86_64"
git-tree-sha1 = "d390e196741abf33522fead5b7d1da23c54cce8b"
os = "windows"

    [[Mongoose.download]]
    sha256 = "bec44ed605a949d8adfdd032982957b575ef998e2e91ee16c4bd84a8f45cb350"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+2/Mongoose.v7.19.0.x86_64-w64-mingw32.tar.gz"
