[[Mongoose]]
arch = "aarch64"
git-tree-sha1 = "2e734e458f7cd26e83ff64d54d433b3f671a9267"
os = "macos"

    [[Mongoose.download]]
    sha256 = "3b57601dca18e84520e7d0092691378eb7c9bf0209176915899c87f6533df869"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+1/Mongoose.v7.19.0.aarch64-apple-darwin.tar.gz"
[[Mongoose]]
arch = "aarch64"
git-tree-sha1 = "de8784158eb56bff7465fa4e6970f087dfafe787"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "ad0a770e7a2c66bd3c1fb96c5f410d70b6d703dd3acf15db106ec073b5a4dd4a"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+1/Mongoose.v7.19.0.aarch64-linux-gnu.tar.gz"
[[Mongoose]]
arch = "aarch64"
git-tree-sha1 = "059e307b91660b1d54bc17664938587c966c83fd"
libc = "musl"
os = "linux"

    [[Mongoose.download]]
    sha256 = "8bcd4ded0761634c5215434d932e6a34245d7923b556809b63023456b1283380"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+1/Mongoose.v7.19.0.aarch64-linux-musl.tar.gz"
[[Mongoose]]
arch = "aarch64"
git-tree-sha1 = "71169aac111d119c050f9f706f980dc905b3e70b"
os = "freebsd"

    [[Mongoose.download]]
    sha256 = "1595767dc7765f5b018c10de558602590cb6affa8f0dd180599a8123f92cbefe"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+1/Mongoose.v7.19.0.aarch64-unknown-freebsd.tar.gz"
[[Mongoose]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e2b4d1b3dea51b842128237b5b37a090e0ea304d"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "b6fa9777b8cf178d451805e1561e280744d21aeaa4d66fbe17e449adf453e781"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+1/Mongoose.v7.19.0.armv6l-linux-gnueabihf.tar.gz"
[[Mongoose]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "cc88420f0550a70b0c1a21d95c73d74d41942a3f"
libc = "musl"
os = "linux"

    [[Mongoose.download]]
    sha256 = "70ff6d8cfbfe37ea1120ff8456fccb265a17a291f7968369ea2aa1b2bc465d3a"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+1/Mongoose.v7.19.0.armv6l-linux-musleabihf.tar.gz"
[[Mongoose]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "165d7c0355345285afda7a8fd0f7a288d5b5d8a7"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "6dad9267d99c0c03e4eb4996e4c21879d7d9ad4dc6a8c3d73f51edcbba0ec18b"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+1/Mongoose.v7.19.0.armv7l-linux-gnueabihf.tar.gz"
[[Mongoose]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3f2d22ca5f0f77a34b0f080216b955109b14f7be"
libc = "musl"
os = "linux"

    [[Mongoose.download]]
    sha256 = "d8a04578607533948236795eacb40ae7c31357613f8af59bb990937b31940626"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+1/Mongoose.v7.19.0.armv7l-linux-musleabihf.tar.gz"
[[Mongoose]]
arch = "i686"
git-tree-sha1 = "4633e87889d915a3a83a2fbcd0676e8006580cb2"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "f9430aa4b94b175ce5955505ed50c62fc2b316edd79a1e9244bb7e951231c6a7"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+1/Mongoose.v7.19.0.i686-linux-gnu.tar.gz"
[[Mongoose]]
arch = "i686"
git-tree-sha1 = "c67c7aa3defafdc896988364807f0218bf40fd2f"
libc = "musl"
os = "linux"

    [[Mongoose.download]]
    sha256 = "979a3515e304ca9cbc50025ffe3a61cfeb4e8d1fdfd738748363059afa5e6a4b"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+1/Mongoose.v7.19.0.i686-linux-musl.tar.gz"
[[Mongoose]]
arch = "i686"
git-tree-sha1 = "ae331a0000eefa72fc4b10ecc9212ea56f8db7dc"
os = "windows"

    [[Mongoose.download]]
    sha256 = "b6d4454a5a98a9bbbb0da208b6f9f2be2e3ce3c069ae8c25444f71fa24bc8fe0"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+1/Mongoose.v7.19.0.i686-w64-mingw32.tar.gz"
[[Mongoose]]
arch = "powerpc64le"
git-tree-sha1 = "aa9815e6b9f61f2d8de6aafcd99aec285ae3ef40"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "5a0410374b396bd91fe957bf49354025d67252f981844285518aa35c4c05eb39"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+1/Mongoose.v7.19.0.powerpc64le-linux-gnu.tar.gz"
[[Mongoose]]
arch = "riscv64"
git-tree-sha1 = "2ac790834e75df02cec3965919335186b9c6b1c1"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "27c49b0e88ff1be5917c78fba03c715820c7b09a6700d600069b886c98868183"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+1/Mongoose.v7.19.0.riscv64-linux-gnu.tar.gz"
[[Mongoose]]
arch = "x86_64"
git-tree-sha1 = "78f2b756101c242f89429f24fcd9094a71b8e74b"
os = "macos"

    [[Mongoose.download]]
    sha256 = "57b9f2112bbcb308d7db5acbb6940f1154e3f156e7862657ad1c94f48074a34d"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+1/Mongoose.v7.19.0.x86_64-apple-darwin.tar.gz"
[[Mongoose]]
arch = "x86_64"
git-tree-sha1 = "09f583f72a83bfb64c47b2737db11bb4200252f5"
libc = "glibc"
os = "linux"

    [[Mongoose.download]]
    sha256 = "90c236a6415871c307d4176b77ee6171ee22725fc37639043cf121412e07563e"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+1/Mongoose.v7.19.0.x86_64-linux-gnu.tar.gz"
[[Mongoose]]
arch = "x86_64"
git-tree-sha1 = "301be9b959e98a33db9022daae3b5c95765ec5c7"
libc = "musl"
os = "linux"

    [[Mongoose.download]]
    sha256 = "7213ff2a58cf19d76dacc9a3f91e1c683a6da684f95476757a0e79dda88566b6"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+1/Mongoose.v7.19.0.x86_64-linux-musl.tar.gz"
[[Mongoose]]
arch = "x86_64"
git-tree-sha1 = "0035b12efe39e6c3763f05212c583ab4e1a55f7f"
os = "freebsd"

    [[Mongoose.download]]
    sha256 = "11e8a6d2e6489a1cad228fb3c90a3b7d3a2161621fc5f34414dac27039d06c77"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+1/Mongoose.v7.19.0.x86_64-unknown-freebsd.tar.gz"
[[Mongoose]]
arch = "x86_64"
git-tree-sha1 = "8ab63c66fe33e018b71ba10d56eb7a6dbe7e5005"
os = "windows"

    [[Mongoose.download]]
    sha256 = "72ccbb142ef46602104f9ad90c8f726593c0cfc3d4cb14ba62f34c1020e78d7b"
    url = "https://github.com/JuliaBinaryWrappers/Mongoose_jll.jl/releases/download/Mongoose-v7.19.0+1/Mongoose.v7.19.0.x86_64-w64-mingw32.tar.gz"
